services:
  postgres:
    container_name: postgres-app-web
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    volumes:
      - .:/app
    command: bash -c "rake db:setup && rackup"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file: .env.example
    environment:
      POSTGRESQL_HOST: postgres-app-web

networks:
  default:
    name: shared_network
    external: true
