services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    volumes:
      - .:/app
    command: rackup
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      POSTGRESQL_HOST: postgres
